Removed ssh and added ssm

diff --git a/.github/workflows/CI_CD.yml b/.github/workflows/CI_CD.yml
--- a/.github/workflows/CI_CD.yml
+++ b/.github/workflows/CI_CD.yml
@@ -90,38 +90,71 @@ jobs:
           docker push $ECR_URL/${{ vars.BACKEND_GATEWAY_IMAGE }}:latest
           docker push $ECR_URL/${{ vars.BACKEND_WORKER_IMAGE }}:latest
 
-      - name: Deploy to EC2
-        uses: appleboy/ssh-action@v0.1.10
-        with:
-          host: 54.163.198.88
-          username: ${{ secrets.EC2_USER }}
-          key: ${{ secrets.EC2_SSH_KEY }}
+            #################################################
+      # Verify SSM Managed Instance
+      #################################################
+      - name: Verify SSM Managed Instance
+        shell: bash
+        run: |
+          STATUS=$(aws ssm describe-instance-information \
+            --filters "Key=InstanceIds,Values=${{ vars.EC2_INSTANCE_ID }}" \
+            --query "InstanceInformationList[0].PingStatus" \
+            --output text)
 
-          script: |
-            cd ~/Workflow-and-Workers/deployments/docker
+          echo "SSM Status: $STATUS"
 
-            ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
-            ECR_URL="$ACCOUNT_ID.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com"
+          if [ "$STATUS" != "Online" ]; then
+            echo "ERROR: EC2 is not online in Systems Manager."
+            exit 1
+          fi
 
-            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
-            | docker login --username AWS --password-stdin $ECR_URL
+      #################################################
+      # Deploy via AWS Systems Manager
+      #################################################
+      - name: Deploy via SSM
+        shell: bash
+        run: |
+          COMMAND_ID=$(aws ssm send-command \
+            --instance-ids "${{ vars.EC2_INSTANCE_ID }}" \
+            --document-name "AWS-RunShellScript" \
+            --comment "Backend Deployment - GitHub Actions" \
+            --timeout-seconds 900 \
+            --parameters '{
+              "commands":[
+                "sudo su - ubuntu -c \"cd /home/ubuntu/Workflow-and-Workers/deployments/docker && ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text) && ECR_URL=${ACCOUNT_ID}.dkr.ecr.'${{ secrets.AWS_REGION }}'.amazonaws.com && aws ecr get-login-password --region '${{ secrets.AWS_REGION }}' | docker login --username AWS --password-stdin ${ECR_URL} && git fetch --all && git checkout '${{ github.ref_name }}' && git pull origin '${{ github.ref_name }}' && docker compose down && docker compose pull && docker compose up -d --remove-orphans && docker system prune -af\""
+              ]
+            }' \
+            --query "Command.CommandId" \
+            --output text)
 
-            echo "Pulling latest code..."
-            git fetch --all
-            git checkout ${{ github.ref_name }}
-            git pull origin ${{ github.ref_name }}
+          echo "Command ID: $COMMAND_ID"
 
+          aws ssm wait command-executed \
+            --command-id "$COMMAND_ID" \
+            --instance-id "${{ vars.EC2_INSTANCE_ID }}"
 
-            echo "Stopping existing containers..."
-            docker compose down
+          STATUS=$(aws ssm get-command-invocation \
+            --command-id "$COMMAND_ID" \
+            --instance-id "${{ vars.EC2_INSTANCE_ID }}" \
+            --query "Status" \
+            --output text)
 
-            echo "Pulling latest images..."
-            docker compose pull
+          echo "Deployment Status: $STATUS"
 
-            echo "Starting updated containers..."
-            docker compose up -d --remove-orphans
+          aws ssm get-command-invocation \
+            --command-id "$COMMAND_ID" \
+            --instance-id "${{ vars.EC2_INSTANCE_ID }}" \
+            --query "StandardOutputContent" \
+            --output text
 
-            echo "Cleaning old Docker resources..."
-            docker system prune -af
+          if [ "$STATUS" != "Success" ]; then
+            echo ""
+            echo "========= ERROR OUTPUT ========="
+            aws ssm get-command-invocation \
+              --command-id "$COMMAND_ID" \
+              --instance-id "${{ vars.EC2_INSTANCE_ID }}" \
+              --query "StandardErrorContent" \
+              --output text
 
-            echo "Deployment completed."
+            exit 1
+          fi
